In [220]:
import pandas as pd
arquivo = pd.read_csv('./wine_dataset.csv')

In [221]:
arquivo.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [222]:
arquivo['style']= arquivo['style'].replace('red',0)

In [223]:
arquivo['style']= arquivo['style'].replace('white',1)

In [224]:
y = arquivo['style']
x= arquivo.drop('style', axis=1)

In [225]:
from sklearn.model_selection import train_test_split

#criando conjunto de dados treino e teste
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size= 0.3)

In [226]:
x_teste

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
5051,8.0,0.240,0.48,6.8,0.047,13.0,134.0,0.99616,3.23,0.70,10.0,5
5,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.99780,3.51,0.56,9.4,5
3178,7.6,0.310,0.49,13.4,0.062,50.0,191.0,0.99890,3.22,0.53,9.0,4
216,8.7,0.625,0.16,2.0,0.101,13.0,49.0,0.99620,3.14,0.57,11.0,5
1348,7.2,0.655,0.03,1.8,0.078,7.0,12.0,0.99587,3.34,0.39,9.5,5
...,...,...,...,...,...,...,...,...,...,...,...,...
4919,7.5,0.290,0.36,15.7,0.050,29.0,124.0,0.99680,3.06,0.54,10.4,5
1524,6.0,0.420,0.19,2.0,0.075,22.0,47.0,0.99522,3.39,0.78,10.0,6
5699,6.3,0.290,0.23,14.2,0.037,24.0,99.0,0.99528,3.08,0.38,10.6,6
5718,6.5,0.400,0.31,3.5,0.046,22.0,147.0,0.99024,3.15,0.31,12.0,7
2594,7.8,0.270,0.34,1.6,0.046,27.0,154.0,0.99270,3.05,0.45,10.5,6

In [227]:
from sklearn.ensemble import ExtraTreesClassifier
#criando modelo
modelo = ExtraTreesClassifier(n_estimators=100)
modelo.fit(x_treino, y_treino)

#Imprimir resultados:
resultado =  modelo.score(x_teste, y_teste)
print("Acuraria :", resultado)

Acuraria : 0.9948717948717949

In [228]:
y_teste

5051    1
5       0
3178    1
216     0
1348    0
       ..
4919    1
1524    0
5699    1
5718    1
2594    1
Name: style, Length: 1950, dtype: int64

In [229]:
x_teste

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
5051,8.0,0.240,0.48,6.8,0.047,13.0,134.0,0.99616,3.23,0.70,10.0,5
5,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.99780,3.51,0.56,9.4,5
3178,7.6,0.310,0.49,13.4,0.062,50.0,191.0,0.99890,3.22,0.53,9.0,4
216,8.7,0.625,0.16,2.0,0.101,13.0,49.0,0.99620,3.14,0.57,11.0,5
1348,7.2,0.655,0.03,1.8,0.078,7.0,12.0,0.99587,3.34,0.39,9.5,5
...,...,...,...,...,...,...,...,...,...,...,...,...
4919,7.5,0.290,0.36,15.7,0.050,29.0,124.0,0.99680,3.06,0.54,10.4,5
1524,6.0,0.420,0.19,2.0,0.075,22.0,47.0,0.99522,3.39,0.78,10.0,6
5699,6.3,0.290,0.23,14.2,0.037,24.0,99.0,0.99528,3.08,0.38,10.6,6
5718,6.5,0.400,0.31,3.5,0.046,22.0,147.0,0.99024,3.15,0.31,12.0,7
2594,7.8,0.270,0.34,1.6,0.046,27.0,154.0,0.99270,3.05,0.45,10.5,6

In [230]:
previsao= modelo.predict(x_teste[0:-1])

In [231]:
print(previsao)

[1 0 1 ... 0 1 1]

In [232]:
total = previsao.size

In [233]:
import collections
acertos = collections.Counter(previsao)[1]

In [234]:
acertos/total*100

75.98768599281684