In [44]:
import pandas as pd
arquivo = pd.read_csv('./wine_dataset.csv')

In [45]:
arquivo.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [46]:
arquivo['style']= arquivo['style'].replace('red',0)

In [47]:
arquivo['style']= arquivo['style'].replace('white',1)

In [48]:
y = arquivo['style']
x= arquivo.drop('style', axis=1)

In [49]:
from sklearn.model_selection import train_test_split

#criando conjunto de dados treino e teste
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size= 0.3)

In [61]:
x_teste

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
5824,6.2,0.345,0.27,10.1,0.056,38.0,187.0,0.99486,3.31,0.56,10.6,5
1143,7.0,0.220,0.30,1.8,0.065,16.0,20.0,0.99672,3.61,0.82,10.0,6
4429,6.6,0.220,0.34,11.6,0.050,59.0,140.0,0.99526,3.22,0.40,10.8,5
1433,6.1,0.400,0.16,1.8,0.069,11.0,25.0,0.99550,3.42,0.74,10.1,7
881,7.6,0.715,0.00,2.1,0.068,30.0,35.0,0.99533,3.48,0.65,11.4,6
...,...,...,...,...,...,...,...,...,...,...,...,...
802,5.1,0.585,0.00,1.7,0.044,14.0,86.0,0.99264,3.56,0.94,12.9,7
5435,8.0,0.270,0.33,1.2,0.050,41.0,103.0,0.99002,3.00,0.45,12.4,6
1846,5.8,0.200,0.27,1.4,0.031,12.0,77.0,0.99050,3.25,0.36,10.9,7
4627,7.5,0.180,0.37,6.2,0.050,21.0,138.0,0.99546,3.20,0.55,10.5,6
3735,7.9,0.180,0.36,5.9,0.058,31.0,132.0,0.99500,3.25,0.52,10.9,6

In [51]:
from sklearn.ensemble import ExtraTreesClassifier
#criando modelo
modelo = ExtraTreesClassifier(n_estimators=100)
modelo.fit(x_treino, y_treino)

#Imprimir resultados:
resultado =  modelo.score(x_teste, y_teste)
print("Acuraria :", resultado)

Acuraria : 0.997948717948718

In [52]:
y_teste[300:303]

955     0
107     0
1795    1
Name: style, dtype: int64

In [53]:
x_teste[300:303]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
955,8.5,0.21,0.52,1.9,0.090,9.0,23.0,0.99648,3.36,0.67,10.4,5
107,6.2,0.63,0.31,1.7,0.088,15.0,64.0,0.99690,3.46,0.79,9.3,5
1795,6.4,0.29,0.44,3.6,0.197,75.0,183.0,0.99420,3.01,0.38,9.1,5

In [54]:
previsao= modelo.predict(x_teste[300:303])

In [55]:
print(previsao)

[0 0 1]

In [ ]:
acc_linear_svc = round(clf.score(X, y) * 100, 2)